Vagrant.configure("2") do |config|

  config.vm.box = "almalinux/9"

  config.vm.define "alma9-1" do |vm|
    vm.vm.hostname = "alma9-1"
    vm.vm.network "private_network", ip: "192.168.121.11"
    vm.vm.provider :libvirt do |libvirt|
      libvirt.uri = 'qemu:///system'
      libvirt.cpus = 4
      libvirt.memory = 1024
      libvirt.nested = false
      libvirt.machine_virtual_size = 40
      libvirt.default_prefix = ""
      
    end
  end

  config.vm.define "alma9-2" do |vm|
    vm.vm.hostname = "alma9-2"
    vm.vm.network "private_network", ip: "192.168.121.12"
    vm.vm.provider :libvirt do |libvirt|
      libvirt.uri = 'qemu:///system'
      libvirt.cpus = 4
      libvirt.memory = 1024
      libvirt.nested = false
      libvirt.machine_virtual_size = 40
      libvirt.default_prefix = ""
    end
  end

  config.vm.define "alma9-3" do |vm|
    vm.vm.hostname = "alma9-3"
    vm.vm.network "private_network", ip: "192.168.121.13"
    vm.vm.provider :libvirt do |libvirt|
      libvirt.uri = 'qemu:///system'
      libvirt.cpus = 4
      libvirt.memory = 1024
      libvirt.nested = false
      libvirt.machine_virtual_size = 40
      libvirt.default_prefix = ""
    end
  end

  config.vm.define "alma9-4" do |vm|
    vm.vm.hostname = "alma9-4"
    vm.vm.network "private_network", ip: "192.168.121.14"
    vm.vm.provider :libvirt do |libvirt|
      libvirt.uri = 'qemu:///system'
      libvirt.cpus = 4
      libvirt.memory = 1024
      libvirt.nested = false
      libvirt.machine_virtual_size = 40
      libvirt.default_prefix = ""
    end
#    vm.vm.provision "ansible" do |ansible|
#      ansible.playbook = "playbook.yml"
#      ansible.inventory_path = "inventory"
#      ansible.limit = "all"
#      ansible.extra_vars = {
#        ANSIBLE_HOST_KEY_CHECKING: 'false'
#      }
#    end
  end

  config.vm.provision "shell", inline: <<-SHELL
    dnf install -y cloud-utils-growpart
    growpart /dev/vda 4
    xfs_growfs /dev/vda4
  SHELL

  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "playbook.yml"
#    ansible.inventory_path = "inventory"
#    ansible.limit = "all"
#    ansible.extra_vars = {
#      ansible_user: 'vagrant',
#      ansible_ssh_private_key_file: "~/.vagrant.d/insecure_private_key"
#    }
  end

end