ENV['VAGRANT_NO_PARALLEL'] = 'true'

Vagrant.configure("2") do |config|
   config.vm.box = "dwedia/almalinux9"
   
   config.vm.define "Alma9-1" do |alma9|
     # Test server 1
     alma9.vm.hostname = "Alma9-1"
     alma9.vm.network "private_network", ip: "192.168.56.10"
     alma9.vm.provider "virtualbox" do |alma9vb|
      alma9vb.name = "alma9-1"
      alma9vb.memory = "2048"
      alma9vb.cpus = "2"
      config.disksize.size = "50GB"
     end
   end

   config.vm.define "Alma9-2" do |alma9|
    # Test server 2
    alma9.vm.hostname = "Alma9-2"
    alma9.vm.network "private_network", ip: "192.168.56.11"
    alma9.vm.provider "virtualbox" do |alma9vb|
     alma9vb.name = "alma9-2"
     alma9vb.memory = "2048"
     alma9vb.cpus = "2"
     config.disksize.size = "50GB"
    end
  end

  config.vm.define "Alma9-3" do |alma9|
    # Test server 3
    alma9.vm.hostname = "Alma9-3"
    alma9.vm.network "private_network", ip: "192.168.56.12"
    alma9.vm.provider "virtualbox" do |alma9vb|
     alma9vb.name = "alma9-3"
     alma9vb.memory = "2048"
     alma9vb.cpus = "2"
     config.disksize.size = "50GB"
    end
  end

  config.vm.define "Alma9-4" do |alma9|
    # Test server 4
    alma9.vm.hostname = "Alma9-4"
    alma9.vm.network "private_network", ip: "192.168.56.13"
    alma9.vm.provider "virtualbox" do |alma9vb|
     alma9vb.name = "alma9-4"
     alma9vb.memory = "2048"
     alma9vb.cpus = "2"
     config.disksize.size = "50GB"
    end
  end

   config.vagrant.plugins = "vagrant-disksize"
   config.vm.provision "ansible" do |ansible|
    ansible.playbook = "playbook.yml"
   end
 end
