---
- name: provision Vagrant VM
  hosts: all
  become: true
  vars:
    desiredTimezone: "Europe/Copenhagen"

  tasks:
  # Setup ssh key
    - name: create .ssh if it does exist
      ansible.builtin.file:
        path: /home/vagrant/.ssh
        state: directory
        mode: '0700'
        owner: vagrant
        group: vagrant

    - name: add vagrant publickey in autorized_keys file
      ansible.builtin.lineinfile:
        path: /home/vagrant/.ssh/authorized_keys
        line: "{{ lookup('file', 'vagrantKey.pub') }}"
        state: present
        create: true
        mode: '0600'
        owner: vagrant
        group: vagrant
        backup: true

# set timezone to Europe/Copenhagen
    - name: set timezone to "{{ desiredTimezone }}"
      ansible.builtin.file:
        src: /usr/share/zoneinfo/{{ desiredTimezone }}
        dest: /etc/localtime
        state: link
      when: ansible_facts['os_family'] == "RedHat"

# install desired software
    - name: install software
      ansible.builtin.dnf:
        name: "{{ item }}"
        state: present
      with_items:
        - vim
        - tree
        - git
      when: ansible_facts['os_family'] == "RedHat"

