Vagrant.configure("2") do |config|
   config.vm.box = "dwedia/almalinux9"
   config.vm.define "Alma9" do |alma9|
     #..
     alma9.vm.hostname = "Alma9"
     alma9.vm.network "private_network", ip: "192.168.56.10"
     alma9.vm.provider "virtualbox" do |alma9vb|
      alma9vb.name = "alma9"
      alma9vb.memory = "2048"
      alma9vb.cpus = "2"
      config.disksize.size = "50GB"
     end
   end
   config.vagrant.plugins = "vagrant-disksize"
   config.vm.provision "ansible" do |ansible|
    ansible.playbook = "playbook.yml"
   end
 end
